# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.

# lint analysis
include: package:lint/analysis_options.yaml

linter:
  rules:
    # Use parameter order as in json response
    #    always_put_required_named_parameters_first: false

    avoid_classes_with_only_static_members: false

    sort_constructors_first: true

    prefer_single_quotes: true

    # Good packages document everything
    public_member_api_docs: true

    always_specify_types: true

    lines_longer_than_80_chars: true
