name: SecurityBearDart
description: Easy and secure way to connect to your computer for maintenance.
version: 1.0.0
homepage: https://github.com/CyBear-Jinni/Security-Bear
author: Guy Luz

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  # Firebase Auth and Firestore SDKs.
  firedart: ^0.8.3
  data_connection_checker: ^0.3.4
  # Collection of lint rules for Dart and Flutter projects
  lint: ^1.3.0

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4
