name: SecurityBearDart
description: Easy and secure way to connect to your computer for maintenance.
version: 1.0.0
homepage: https://github.com/CyBear-Jinni/Security-Bear
author: Guy Luz

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  # Firebase Auth and Firestore SDKs.
  firedart: ^0.8.3
  # Functional programming thingies, let you use multiple return types
  dartz: ^0.9.2
  # Checks for an internet connection by opening a socket
  data_connection_checker: ^0.3.4
  # Collection of lint rules for Dart and Flutter projects
  lint: ^1.3.0
  # For the injection, allow accessing an object from anywhere in an App
  get_it: ^5.0.1
  # Allow returning more than one type of object
  equatable: ^1.2.5
  # Convert enum to string
  enum_to_string: ^1.0.13
  # Key-value database
  hive: ^1.4.4+1
  # Process run helpers for Linux/Win/Mac.
  process_run: ^0.11.0+2
  # Provides parse, inspect, and manipulate stack traces
  stack_trace: ^1.9.5


dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4
  # Library for mocks
  mockito: ^4.1.3
  hive_generator: ^0.8.1
  build_runner:



