name: security_bear_dart
description: Easy and secure way to connect to your device for maintenance.
version: 1.1.1
homepage: https://github.com/CyBear-Jinni/Security-Bear
author: Guy Luz

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Functional programming thingies, let you use multiple return types
  dartz: ^0.9.2
  # Convert enum to string
  enum_to_string: ^2.0.1
  # Allow returning more than one type of object
  equatable: ^2.0.2
  # Firebase Auth and Firestore SDKs.
  firedart: ^0.9.0+1
  # For the injection, allow accessing an object from anywhere in an App
  get_it: ^7.1.3
  # Key-value database
  hive: ^2.0.4
  # Checks for an internet connection by opening a socket
  internet_connection_checker: ^0.0.1+1
  # Collection of lint rules for Dart and Flutter projects
  lint: ^1.5.3
  # Process run helpers for Linux/Win/Mac.
  process_run: ^0.12.1
  # Provides parse, inspect, and manipulate stack traces
  stack_trace: ^1.10.0


dev_dependencies:
  build_runner:
  hive_generator: ^1.1.0
  # Library for mocks
  mockito: ^5.0.9
  pedantic: ^1.11.0
  test: ^1.17.5



