name: network-manager-dart
base: core18
version: '0.2'  # Just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

  #grade: stable # must be 'stable' to release into candidate/stable channels
  #confinement: strict # use 'strict' once you have the right plugs and slots

grade: devel  # Must be 'stable' to release into candidate/stable channels
confinement: devmode
#architectures: [all]

parts:
  network-manager-dart:
    plugin: dump
    source: .
    override-build: |
      scripts/bashScripts/nativeExecutableMaker.sh  # Downloading dart-sdk for the correct architecture

      rm -r SecurityBearDart

      snapcraftctl build
      #sudo apt install network-manager

    build-packages:
      - wget
      - unzip
      - git
    stage-packages:
      - crda
      - iputils-arping
      - iw
      - libbluetooth3
      - libcap2-bin
      - libfribidi0
      - libgudev-1.0-0
      - libjansson4
      - libmbim-glib4
      - libmbim-proxy
      - libmm-glib0
      - libndp0
      - libnewt0.52
      - libnl-3-200
      - libnl-genl-3-200
      - libnm0
      - libpam-cap
      - libpcap0.8
      - libpcsclite1
      - libpipeline1
      - libpolkit-agent-1-0
      - libpolkit-gobject-1-0
      - libqmi-glib5
      - libqmi-proxy
      - libslang2
      - libteamdctl0
      - libusb-1.0-0
      - modemmanager
      - policykit-1
      - ppp
      - pptp-linux
      - usb-modeswitch
      - usb-modeswitch-data
      - wireless-regdb
      - wpasupplicant
      - libatm1

      - network-manager-pptp
      - network-manager

      - wireless-tools

apps:
  network-manager-dart:
    command: main.exe $SNAP
    #daemon: simple
    plugs: [network, network-bind, hardware-observe]
